/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TeliaCarousel {
        "timerDelay": number;
    }
    interface TeliaCarouselSlide {
        "active": boolean;
        "alt": string;
        "src": string;
        "variant": 'cover' | 'contain';
    }
}
export interface TeliaCarouselSlideCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTeliaCarouselSlideElement;
}
declare global {
    interface HTMLTeliaCarouselElement extends Components.TeliaCarousel, HTMLStencilElement {
    }
    var HTMLTeliaCarouselElement: {
        prototype: HTMLTeliaCarouselElement;
        new (): HTMLTeliaCarouselElement;
    };
    interface HTMLTeliaCarouselSlideElement extends Components.TeliaCarouselSlide, HTMLStencilElement {
    }
    var HTMLTeliaCarouselSlideElement: {
        prototype: HTMLTeliaCarouselSlideElement;
        new (): HTMLTeliaCarouselSlideElement;
    };
    interface HTMLElementTagNameMap {
        "telia-carousel": HTMLTeliaCarouselElement;
        "telia-carousel-slide": HTMLTeliaCarouselSlideElement;
    }
}
declare namespace LocalJSX {
    interface TeliaCarousel {
        "timerDelay"?: number;
    }
    interface TeliaCarouselSlide {
        "active"?: boolean;
        "alt"?: string;
        "onCarouselSlideLoaded"?: (event: TeliaCarouselSlideCustomEvent<any>) => void;
        "src"?: string;
        "variant"?: 'cover' | 'contain';
    }
    interface IntrinsicElements {
        "telia-carousel": TeliaCarousel;
        "telia-carousel-slide": TeliaCarouselSlide;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "telia-carousel": LocalJSX.TeliaCarousel & JSXBase.HTMLAttributes<HTMLTeliaCarouselElement>;
            "telia-carousel-slide": LocalJSX.TeliaCarouselSlide & JSXBase.HTMLAttributes<HTMLTeliaCarouselSlideElement>;
        }
    }
}
